### ISSUE TITLE
冥婚

### ISSUE THREAD

**Issue by mrhso** [FurDevsCN/who-is-harry#5]
https://www.bilibili.com/read/cv16184103
![image](https://user-images.githubusercontent.com/13294467/163719851-73cb2345-81dc-4ef8-8722-c10251661305.png)

**Comment by hanbings** [comment]
太阴间了

**Comment by colour93** [comment]
更新
https://github.com/FurDevsCN/who-is-harry/commit/66497fdcf43a77e6e5313ff4ca2ed668bf7a42d9
